ash-project/ash_graphql

- mix.exs
Updates Ash dependency to `~> 1.0` to reduce version bumping.
> chore: Specify ash dependency to be ~> 1.0 until official 2.0 release

- config/config.exs
- lib/ash_graphql.ex
- lib/graphql/resolver.ex
- test/errors_test.exs
- test/read_test.exs
- test/support/registry.ex
- test/support/resources/multitenant_post_tag.ex
- test/support/resources/multitenant_tag.ex
- test/support/resources/post.ex
I've played a bit with [example project|https://github.com/ash-project/ash_example], and found an issue.
I've created a simple ticket with id `99bb4bec-b8ea-494e-83da-1f706c44a1e1`, and then tried to execute this query:
```graphql
query {
getTicket(id: "99bb4bec-b8ea-494e-83da-1f706c44a1e1") {
id
description
response
representative {
id
}
reporter {
id
}
subject
status
}
}
```
It fails because tenant is not set in the context:
[old.log](https://github.com/ash-project/ash_graphql/files/8665107/old.log)
But instead of returning `Something went wrong` in `errors` field, the request is failed with 500 error.
I've changed `dataloader` behavior from raising an exception to returning a tuple `{:error, error}`, so this error could be handled by existing `to_resolution` function.
Now fields which …
> fix: Handle error if multitenant resource was fetched without tenant being set

- documentation/how_to/use-enums-with-graphql.md
The Code Snippet gave me a compile error, telling me that `one_of` was not a valid option
> docs: Fix constraints example in enum how_to

- lib/resource/resource.ex
- test/attribute_test.exs
- test/read_test.exs
Maps uuid action arguments to ID GraphQL type – they were being mapped to the String GraphQL type.
> fix: map uuid action arguments to ID type

- lib/resource/resource.ex
- test/support/resources/post.ex
The function `manage_pkey_fields` that calls `pkey_fields` could not handle a single value being returned as it tries to map over the result.
> fix: always return a list from pkey_fields

- lib/graphql/dataloader.ex
- test/read_test.exs
- test/support/resources/post.ex
Prior to this patch, an error was raised `* No such attribute [resource]_id`, since the data loader attempted to load the relationship via a related id field, which does not exist for manual relationships.
> improvement: support manual relationships

- lib/resource/resource.ex
Check the `TODO:`s for a couple of additional places where adding descriptions would require supporting them in core. Operators maybe not relevant, but `Ash.Resource.Calculation.Argument` probably worthwhile. See https://github.com/ash-project/ash/blob/de943509f73ff0c6ef3749feb3cc6ab6e4d99d2d/lib/ash/resource/calculation/calculation.ex#L103
This is not 100% comprehensive, there are a lot of `InputObjectDefinition`s that could be candidates.
> improvement: pass `description` through to Absinthe in more cases

- .formatter.exs
- lib/resource/info.ex
- lib/resource/resource.ex
Adds the ability to specify which fields a filter should be made available for:
```elixir
graphql do
filterable_fields [:name, :age]
end
```
> feat: add `filterable_fields` to limit generated filters

- test/alias_test.exs
- test/support/resources/post.ex
After working a bit more with aliases today I found a couple more problems, I tried to check the code, but had a hard time figuring out what happened. 
Instead I created a couple tests that should check most alias cases. During this progress the relationship test also gave me this error 
```elixir
13:23:38.112 [warning] `b6c6c824-999f-4f50-96bb-e2be5a7401f3`: AshGraphql.Error not implemented for error:
** (Ash.Error.Framework) Framework Error
* Assumption failed: Invalid return from request resolver for "fetch AshGraphql.Test.Post.read" data:
Got:
:error
This should not be possible, please report a detailed bug at:
https://github.com/ash-project/ash/issues/new?assignees=&labels=bug%2C+needs+review&template=bug_report.md&title=
(ash 2.9.26) lib/ash/engine/request.ex:1224: …
```
> add tests for graphql aliases

- lib/graphql/errors.ex
- lib/graphql/resolver.ex
- test/support/test_helpers.ex
Use Logger.warning instead of Logger.warn, [which is deprecated as of elixir 1.15](https://github.com/elixir-lang/elixir/blob/v1.15/CHANGELOG.md#logger-2).
Logger.warning [is available since elixir 1.11](https://hexdocs.pm/logger/1.15.0/Logger.html#warning/2), and since [this project requires at least elixir 1.11](https://github.com/ash-project/ash_graphql/blob/main/mix.exs#L14), this is a safe change.
> fix: fix Logger deprecations for elixir 1.15

- lib/resource/resource.ex
- test/attribute_test.exs
- test/support/resources/constrained_map.ex
- test/support/resources/map_types.ex
> fix: wrap type in non-null reference if allow_nil? is set to false

- test/read_test.exs
- test/support/resources/comment.ex
- test/support/resources/post.ex
An error occurs at compile time when an aggregate of a calculation is defined:
```
== Compilation error in file test/support/schema.ex == ** (MatchError) no match of right hand side value: {:error, "Must provide field type for max"}
lib/resource/resource.ex:2278: AshGraphql.Resource.filterable?/2
(elixir 1.15.4) lib/enum.ex:4265: Enum.filter_list/2
(elixir 1.15.4) lib/enum.ex:4266: Enum.filter_list/2
lib/resource/resource.ex:2229: AshGraphql.Resource.aggregate_filter_fields/2
lib/resource/resource.ex:2195: AshGraphql.Resource.resource_filter_fields/2
lib/resource/resource.ex:1159: AshGraphql.Resource.args/5
lib/resource/resource.ex:425: anonymous fn/6 in AshGraphql.Resource.queries/5
(elixir 1.15.4) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
```
> test: add failing test for an aggregate of a calculation

- lib/resource/resource.ex
I had to do some front-end work today and felt like this would be better. The spec doesn't say if it has to be nullable or non-nullable. Same with the Edge, I don't think it would make sense to have null values as edges. 
I couldn't think of a situation where we would actually return null for a node, pls correct me if I'm wrong.
> refactor: make the node in relay edges non-null

- documentation/tutorials/getting-started-with-graphql.md
As asked in ash-project/ash_hq#122. Ensured locally that it works with everything up to that point.
- ~~[ ] Bug fixes include regression tests~~ N/A
- ~~[ ] Features include unit/acceptance tests~~
> Removed mention of Context and Dataloader in Getting Started with Graphql

- lib/graphql/resolver.ex
- test/generic_actions_test.exs
- test/support/resources/post.ex
> fix: make sure generic actions are authorized

- documentation/topics/relay.md
- lib/api/api.ex
- lib/ash_graphql.ex
- lib/error.ex
- lib/graphql/resolver.ex
- lib/resource/resource.ex
- lib/subscriptions.ex
- test/relay_ids_test.exs
- test/support/relay_ids/api.ex
- test/support/relay_ids/registry.ex
- test/support/relay_ids/resources/post.ex
- test/support/relay_ids/resources/resource_with_no_primary_key_get.ex
- test/support/relay_ids/resources/user.ex
- test/support/relay_ids/schema.ex
Add support for Relay global IDs and the `node` query, see https://relay.dev/graphql/objectidentification.htm
> Relay refetching support

- lib/graphql/resolver.ex
- lib/resource/resource.ex
- test/relay_ids_test.exs
Slight API improvement over #106.
This makes it more ergonomic to partially match on the return value (and it also makes it more explicit by explicitly labeling the two parts).
Also add tests for relay id encoding/decoding.
> improvement: return a map from decode_relay_id/1

- lib/resource/resource.ex
- test/errors_test.exs
First round of implementation of what was discussed in #105 
This PR makes result types non-nullable.
> First round of improvements around non-nullability

- config/config.exs
- documentation/tutorials/getting-started-with-graphql.md
- lib/resource/resource.ex
- test/create_test.exs
- test/destroy_test.exs
- test/update_test.exs
As discussed in #105 and #110, put this behind an opt-in configuration to avoid breaking existing code.
The ID in update mutations is always non-null if non-null mutation arguments are allowed, while input is non-null if it's allowed _and_ there is at least a non-null field in the input.
Document the newly added config variable in the getting started guide.
> improvement: make mutation arguments non-null

- .formatter.exs
- documentation/dsls/DSL:-AshGraphql.Resource.md
- documentation/topics/relay.md
- lib/graphql/id_translator.ex
- lib/resource/mutation.ex
- lib/resource/query.ex
- lib/resource/resource.ex
- test/relay_ids_test.exs
- test/support/relay_ids/resources/post.ex
- test/support/relay_ids/resources/user.ex
Adds a new option for queries and mutations that defines which arguments or attributes will use a global Relay ID and their type. This allows automatically decoding them before hitting their action.
> feat: add Relay ID translation in mutation and queries

- lib/resource/resource.ex
Allow DataLayer Filters (like, ilike from postgres in filter) 
depends on 
* https://github.com/ash-project/ash_postgres/pull/205
* https://github.com/ash-project/ash/pull/874
Very naive first implementation. It works in my project already, but I feel I'm probably missing some edge cases.
Somehow, the filter is already only applied to String attributes, but I'm not completely sure why.
> Data layer functions

- lib/resource/resource.ex
- test/errors_test.exs
- test/support/root_level_errors_api.ex
- test/support/root_level_errors_schema.ex
Building upon #110, this restores the old behaviour of the result being nullable when root level errors are present.
While the result is guaranteed to not be nullable in standard conditions (since either result or errors are always present), when errors are moved to the root level it could become null, so declaring it non-nullable propagates the null up to the data field.
This actually causes compatibility problems with some client libraries (e.g. Relay) that expect the inner result to be null, _not_ data, if there's an error.
This also adds dedicated RootLevelErrors versions of the Api and the Schema since the configuration is accessed at compile time now, so put_env was not enough to test them correctly.
> fix: make results nullable again if root level errors are enabled

- lib/resource/info.ex
- lib/resource/resource.ex
There is `hide_fields` option. How about adding `show_fields` option that if present acts like an explicit list of allowed fields?
My use case is that I want to move graphql section out of resources into separate folder with `Spark.Dsl.Fragment`. But it means that looking just at that file you won't have context about present fields. With this you would have some idea.
Plus it is good from security perspective since you might add an attribute and forget to add it to `hide_fields`.
> improvement: add `show_fields` option as explicit fields whitelist

- .formatter.exs
- documentation/dsls/DSL:-AshGraphql.Resource.md
> fix: add `show_fields` to `spark_locals_without_parens` in formatter

- lib/resource/resource.ex
- test/resource_test.exs
- test/support/resources/post.ex
As mentioned in the upgrade guide, the point of dropping auto generation of types was to avoid conflicts when two arguments had the same name but different types. Now that we require explicit generation, we can actually support that usecase for, e.g., arguments with the same name but different types in create/update mutations.
> fix: don't deduplicate argument types by argument name

- .formatter.exs
- documentation/dsls/DSL:-AshGraphql.Resource.md
- lib/graphql/resolver.ex
- lib/resource/info.ex
- lib/resource/resource.ex
- lib/resource/verifiers/verify_paginate_relationship_with.ex
- test/paginate_test.exs
- test/relationship_pagination_test.exs
- test/support/domain.ex
- test/support/resources/actor.ex
- test/support/resources/actor_agent.ex
- test/support/resources/agent.ex
- test/support/resources/award.ex
- test/support/resources/movie.ex
- test/support/resources/movie_actor.ex
- test/support/resources/post.ex
- test/support/resources/review.ex
Resources can now define how their relationships are paginated. This is a property of the Graphql type of the resource and it allows arbitrarily nested paginated relationships.
The PR also contains a fix to the existing pagination, which was not working correctly when a keyset strategy was used with an action that also supported offset pagination.
Close #131
> feat: relationship pagination

- test/relationship_pagination_test.exs
- test/support/resources/movie.ex
Following on ash-project/ash#1234, this PR adds tests to verify that relationships can be queried on the results of GraphQL queries and mutations.
Querying paginated relationships on the result of deletions doesn't correctly work yet.
Indeed, Ash currently queries relationships using a lateral join but after the resource deletion has happened, so it looks like nothing is related.
> chore: add tests on paginated relationships

- lib/resource/resource.ex
I had this fail because I created a new Type (subtype of map with a field that was an enum)
> fix: use checked constraints

- lib/resource/info.ex
- test/support/resources/tag.ex
The calling function passes in `field.name`, the `filterable_field?` function should not attempt to access the name again
This fixes a compilation error when using the `filterable_fields` config option anywhere in your app
(well technically I didn't add any test, but adding the `filterable_fields` option to a test resource causes the app to not compile anymore without the code change)
> bugfix: Fix check for checking if a field is filterable or not

- lib/default_error_handler.ex
Current implementation doesn't support basic case of list of atoms as errors.
```
** (ArgumentError) cannot convert the given list to a string.
To be converted to a string, a list must either be empty or only
contain the following elements:
* strings
* integers representing Unicode code points
* a list containing one of these three elements
Please check the given list or call inspect/1 to get the list representation, got:
[:option1, :option2, :option3]
```
> fix: error handling list of atoms

- lib/mix/tasks/ash_graphql.install.ex
This keeps consistency with AshJsonApi, which generates its router in the web module namespace as well
> chore: Set up GraphQL schema file in the web module namespace

- documentation/topics/use-enums-with-graphql.md
- documentation/topics/use-maps-with-graphql.md
Small fix in the documentation to use `graphql_type/1` to have correct signature.
> docs: Use correct arity for graphql_type

- lib/mix/tasks/ash_graphql.install.ex
This PR adds absinthe in `.formatter.exs` when the installer is used.
Thanks to that the formatter will avoid adding parenthesis to `import_types`.
> feat: Add absinthe dependency and plugin in formatter of installer

- lib/domain/domain.ex
- lib/igniter.ex
- lib/subscription/batcher.ex
Dialyzer did have a problem with the batcher code. I just haven't used dialyzer before, so i looked at the wrong ouptut.
> fix: dyalizer and igniter deprecations

- lib/graphql/resolver.ex
- lib/subscription/batcher.ex
- lib/subscription/notifier.ex
- lib/subscription/runner.ex
> feat: remove unused data in subscription batcher

- test/support/resources/post.ex
This PR adds some actions (read, create, update, destroy, action) to a test resource (Post) to trigger a bug where AshGraphql will ignore some invalid argument names in read and custom actions.
Note: This doesn't fixes the bug, only makes the code stop compiling by triggering it.
> chore: Add invalid actions argument names to test resources

- test/custom_paginate_test.exs
- test/support/domain.ex
- test/support/resources/channel/calculations/filter_by_actor_messages_calculation.ex
- test/support/resources/channel/changes/create_message_user.ex
- test/support/resources/channel/channel.ex
- test/support/resources/channel/message.ex
- test/support/resources/channel/message_viewable_user.ex
- test/support/resources/channel/types/page_of_filter_by_actor_messages.ex
> chore: provide a test for relationship filter by actor

- lib/graphql/resolver.ex
- lib/resource/resource.ex
Infer that their return type is `:boolean` and they always return `true`. We considered returning `null` but that's also returned when the query/mutation fails and might convey the wrong information.
> improvement: Support generic actions without a return type.

- lib/error.ex
> improvement: Implement `AshGraphql.Error` for AshAuthentication errors.

- documentation/tutorials/getting-started-with-graphql.md
-  Correct an error in the documentation: The playground  was before the enddpoint rout, causing "No Query document supplied" 
- Moved the playground route  before the endpoint route
> Move the playground route  before the endpoint route

- lib/ash_graphql.ex
- lib/graphql/resolver.ex
- lib/subscriptions.ex
- test/relay_ids_test.exs
- test/support/relay_ids/domain.ex
- test/support/relay_ids/resources/comment.ex
- test/support/relay_ids/resources/post.ex
- test/support/relay_ids/resources/user.ex
Similar to what was done in 2886e0c8c1aea3c943d for selections, we have to do the same thing for loads to make them work with interface fragments (including the Relay node interface).
> fix: load relationships and calculations in fragments

- documentation/dsls/DSL-AshGraphql.Domain.md
- documentation/dsls/DSL-AshGraphql.Resource.md
- documentation/topics/handle-errors.md
- lib/graphql/errors.ex
- lib/graphql/resolver.ex
- lib/resource/info.ex
- lib/resource/resource.ex
- test/errors_test.exs
- test/support/domain.ex
- test/support/resources/error_handling.ex
similarly to error handling in domains, we can allow the `error_handler` option also in resources, so that only errors coming from the specific resource can be customized
> feat: error handling in resources

- documentation/topics/handle-errors.md
- lib/graphql/errors.ex
- lib/graphql/resolver.ex
- test/errors_test.exs
- test/support/resources/error_handling.ex
Add the action name in the context
> feat(errors): carry action name in context

- documentation/dsls/DSL-AshGraphql.Resource.md
- lib/resource/resource.ex
- test/errors_test.exs
- test/support/resources/post.ex
Do not apply the default error handler when a custom error handler has been defined on the domain and no error handler was specified on the resource.
The way this was achieved was by not setting the default resource level `error_handler` to `AshGraphql.DefaultErrorHandler`. We already have this behaviour at the domain level, giving the user the experience of the default error handler, by default.
At the resource level, the user has the option to define their own error handler, which is applied, or not.
This bug was causing an issue in our codebase, since we do not want the default error handler applied at all, and we would have had to set it explicitly to `nil` in every resource to get the behaviour we want.
Resolves #260
> fix: default error handling

- test/resource_test.exs
- test/support/domain.ex
- test/support/resources/resource_with_type_inside_type.ex
- test/support/types/type_with_type_inside.ex
- test/support/types/type_within_type_unreferenced_submap.ex
Added test that fails when using a sub-type that is not otherwise exposed in the schema.
Absinthe complains about unreferenced type.
Adding type to any argument will make test pass again.
Or properly traversing type will make test work.
> Add test that exposes failure to traverse nested otherwise unreferenced types

- lib/resource/resource.ex
Fixed two things:
- Pulled constraint from right place (was a bug where it tried to pull constraints from the outer constraints and not from each individual new attribute)
- Utilize the maybe null wrapper and default to not wrapping null unless explicitly supplying nil items
Open question: Maybe we **should** actually default to `nil_items?: false` (as in not use my defensive default to `true`) so that we get the same default setting as for attributes?
It might be confusing that array types does not produce non_null inner items for self defined NewType maps.
Alternatively, that is a bug that needs to be fixed in Ash.
If so then maybe we should make a bug in Ash and reference that bug from this comment I put in?
> Properly non_null() inner items in list when constraint is supplied for arrays in NewType of :map

- test/resource_test.exs
- test/support/resources/comment.ex
> add tests for using args in calculations for filters and sorts

- lib/graphql/resolver.ex
- test/errors_test.exs
---
Hey there :wave: 
Thanks for working on ash!
Similar report  to https://github.com/mtrudel/bandit/issues/413.
`crash_reason` metadata useful for `Logger` [handlers](https://hexdocs.pm/logger/main/Logger.html#module-erlang-otp-handlers), so that they can receive the original exception values in addition to the formatted error string.
Discovered this while testing [`tower`](https://github.com/mimiquate/tower) alongside `ash`, but this could be useful for any other exception tracker using a `:logger` handler.
Elixir Logger docs:
https://hexdocs.pm/logger/1.17.3/Logger.html#module-metadata
Examples:
- `plug_cowboy`
- https://github.com/elixir-plug/plug_cowboy/blob/ced253f035f2a07ebed17cfacb64d4f16357a750/lib/plug/cowboy/translator.ex#L42-L46
- …
> feat: allows `:logger` handlers to know original exception

- lib/error.ex
- test/errors_test.exs
Follow-up to https://github.com/ash-project/ash/pull/1960. Handle both `field` and `fields` in `InvalidQuery` error.
> fix: handle invalid query error different formats

- lib/ash_graphql.ex
- lib/domain/domain.ex
- lib/graphql/resolver.ex
- lib/resource/resource.ex
- test/subscription_test.exs
- test/support/relay_domain.ex
- test/support/relay_schema.ex
- test/support/resources/relay_subscribable.ex
Closes #306 
Currently, if attempting to subscribe to a destroy event, the message that is received has the shape of something like:
```json
"myResource": {
"destroyed": "{myUUID}"
}
```
However, if a user has a schema with `relay_ids?: true`, this is the wrong type of ID, as it doesn't get encoded as a relay id.
This PR addresses that by passing the `relay_ids?` value down through the domains and resources, and eventually to the `resolve/2` function which gets added to the Absinthe middleware. When encoding the id for a `:destroy` action, the `relay_ids?` setting will now be respected.
---
I couldn't find a way to change the `relay_ids?` value at runtime during the test, so this unfortunately requires setting up a whole new `RelaySchema` and associated `RelayDomain` and …
> Support for returning relay encoded id when subscribing to destroy events

- test/gf_test.exs
- test/support/gf/active_member_policy.ex
- test/support/gf/ash_graphql_schema.ex
- test/support/gf/attendee.ex
- test/support/gf/domain.ex
- test/support/gf/event.ex
- test/support/gf/group.ex
- test/support/gf/member.ex
- test/support/gf/types/member_status.ex
Elixir Forum reference: https://elixirforum.com/t/not-found-in-nil-exception-after-ash-upgrade/70722/15
```
15:17:28.414 [error] 4291beb8-4a54-4fb1-b9bd-cdd57dba42b1: Exception raised while resolving query.
** (Ash.Error.Unknown) 
Bread Crumbs:
> Exception raised in: GF.Event.read> Exception raised in: GF.Attendee.read
Unknown Error
* ** (KeyError) key :to_tenant not found in: nil
If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
(ash 3.5.8) lib/ash/policy/check/expression.ex:3: Ash.Policy.Check.Expression.try_strict_check/3
(ash 3.5.8) lib/ash/policy/policy.ex:183: Ash.Policy.Policy.fetch_or_strict_check_fact/2
(ash 3.5.8) lib/ash/policy/policy.ex:431: Ash.Policy.Policy.handle_constants/2
(ash 3.5.8) lib/ash/policy/policy.ex:404: …
```
> Reproduce `(KeyError) key :to_tenant not found in: nil`

- documentation/dsls/DSL-AshGraphql.Domain.md
- documentation/dsls/DSL-AshGraphql.Resource.md
- lib/resource/mutation.ex
- lib/resource/query.ex
It is mostly documentation thing but also there is a small fix - `modify_resolution` was defined specifically only for `get`, `create` and `action`, not for other queries/mutations, even thought the code handles presence of `modify_resolution` in all action types.
> fix: define shared mutations options

- .formatter.exs
- documentation/dsls/DSL-AshGraphql.Domain.md
- documentation/dsls/DSL-AshGraphql.Resource.md
- lib/graphql/resolver.ex
- lib/resource/mutation.ex
- lib/resource/resource.ex
- test/create_test.exs
- test/generic_actions_test.exs
- test/support/resources/post.ex
- test/update_test.exs
Adds `args` option to specify action attributes/arguments that should get their own arguments in the mutation method instead being passed in an input object.
(Also small fix - those [lines](https://github.com/ash-project/ash_graphql/blob/1e5149b0379d2815a4ced2f9f8871761a5b58832/lib/resource/resource.ex#L850-L855) that came from logic before my refactor meant that for generic action it's arguments were used to check if input needs to be non-null, but `action.arguments` and `mutation_fields` are different things - action arguments won't contain `Absinthe.Blueprint.Schema.FieldDefinition`, so based on that I assume that generic action input object was always nullable.)
> improvement: add `args` option to mutations

- lib/igniter.ex
- test/mix/tasks/ash_graphql_install_test.exs
Previously, the default playground interface was set to `:playground` which uses graphql-playground. However, this uses a deprecated JavaScript API which means that it does not work on modern versions of chrome. It also seems that the library is no longer maintained, so the chances of this being fixed in a future release are slim.
The result of this, is that tooltips do not disappear, making the application seem broken. Whilst this isn't a direct issue of this library, I think it gives a bad impression when things are broken out of the box.
This commit changes the generated interface to graphiql (using the `:simple` interface). There is also an `:advanced` interface option, but that also points to an unmaintained library which didn't work out of the box. …
> fix: change default playground interface

- lib/graphql/resolver.ex
- lib/resource/resource.ex
- test/paginate_test.exs
> make pagination metadata more robust for offset based pagination

- lib/graphql/resolver.ex
- lib/resource/resource.ex
In a simple data layer, a resource with an array-type attribute does not properly set the middleware fields correctly. i.e.,
```
attribute :results, {:array, UnionType} do
....
end
```
> fix: handling of attribute with array type in middleware for field function

- test/create_test.exs
- test/support/resources/post.ex
Defining an argument and argument_input_type like this:
```elixir
argument :foo, :integer
argument_input_types foo: :string
```
Results in the error:
```
Argument "input" has invalid value $input.
In field "foo": Expected type "Int", found "1".
```
> Bug: `argument_input_types foo: :string` is ignored

- documentation/dsls/DSL-AshGraphql.Domain.md
- documentation/dsls/DSL-AshGraphql.Resource.md
- lib/resource/resource.ex
- lib/resource/subscription.ex
- test/subscription_test.exs
- test/support/resources/relay_subscribable.ex
Adds support for passing relay id's to subscription read_actions.
Closes #348 
Fortunately this was pretty straight forward and just required adding the `id_translation_middleware` for when subscriptions are setup and created.
PR also includes a test, which required making some changes to the test relay_schema.
> [Relay] Add support for relay_id_translation on GraphQL subscriptions

- lib/ash_graphql.ex
- lib/resource/resource.ex
After trying `mix ash.codegen --check` in my CI pipeline (but also locally), I noticed instabilities in the generated GraphQL SDL schema, for example:
```diff
diff --git a/priv/schema.graphql b/priv/schema.graphql
index a708353..c6e0e1b 100644
--- a/priv/schema.graphql
+++ b/priv/schema.graphql
@@ -22,25 +22,25 @@ input BulkSyncPhotosInput {
id: ID
timestamp: DateTime
comment: String
-  deleted: Boolean
-  timezone: String
syncStatus: String
projectId: ID
-  rotationAngle: Int
mimeType: String
-  sha256Hash: String
fileUploadStatus: String
+  timezone: String
+  deleted: Boolean
+  rotationAngle: Int
+  sha256Hash: String
}
input BulkSyncEventsInput {
id: ID
comment: String
-  duration: Int
-  deleted: Boolean
-  startTime: DateTime
-  timezone: String
syncStatus: String
+  startTime: …
```
> Fix SDL stability
