ash-project/ash_graphql

documentation/introduction/getting_started.md
=> Updated documentation on  Connect your schema - Using Plug

.formatter.exs, lib/graphql/resolver.ex, lib/resource/mutation.ex, lib/resource/query.ex, lib/resource/resource.ex
=> Identities for gets

documentation/introduction/getting_started.md
- Tiny fix noticed when copy pasting.
=> Getting started GraphiQL code example fix

lib/resource/resource.ex
I sorted the list and added the decimal type
=> support decimal type

.formatter.exs, documentation/introduction/getting_started.md, lib/graphql/resolver.ex, lib/resource/query.ex, lib/resource/resource.ex, test/read_test.exs, test/support/api.ex, test/support/resources/post.ex, test/support/resources/user.ex
=> feat: add read_one query

lib/resource/resource.ex
https://github.com/ash-project/ash/pull/220 uses allow_nil? from this PR to generate type of calculation
=> improvement: generate type based on allow_nil?

lib/resource/query.ex, lib/resource/resource.ex, test/support/resources/user.ex
Issue: https://github.com/ash-project/ash_graphql/issues/15
I also added a `maybe_wrap_non_null/2` function to make it simpler to wrap types in non_null. Let me know if you want any changes to that.
=> improvement: add allow_nil? to queries

lib/resource/resource.ex, test/read_test.exs, test/support/resources/post.ex
Adds missing float type support!
=> improvement: Add float type

lib/resource/resource.ex, test/create_test.exs, test/support/api.ex, test/support/resources/post.ex, test/support/resources/post_tag.ex, test/support/resources/tag.ex
=> test: Added a test case to managed_relationship with a many_to_many resource

lib/resource/resource.ex
=> fix: Check for nil rather than the value as `not` does not accept a function

test/destroy_test.exs, test/support/resources/post.ex
No fix but a test that once fixed _should hopefully_ compile and test the functionality.
Might want to be able to check that is is indeed still left in the database too?
=> test: add a test to demonstrate an issue with soft deletes in GraphQL

lib/graphql/resolver.ex, test/destroy_test.exs, test/support/resources/post.ex
=> fix: fix changeset.errors on destroy

test/create_test.exs, test/destroy_test.exs, test/support/resources/post.ex, test/update_test.exs
=> failing test for root errors

.formatter.exs, lib/resource/resource.ex, test/resource_test.exs, test/support/registry.ex, test/support/resources/no_object.ex
=> improvement: setup generate_object? setting on resource

lib/resource/resource.ex
=> fix: Types with no constraints crash

documentation/authorization.md, lib/error.ex, test/errors_test.exs, test/support/resources/user.ex
=> feat: add policy breakdowns option

lib/error.ex
=> improvement: Add Ash.Error.Changes.InvalidChanges AshGraphql implementation

documentation/how_to/authorize-with-graphql.md, documentation/how_to/use-enums-with-graphql.md, documentation/how_to/use-json-with-graphql.md, documentation/tutorials/getting-started-with-graphql.md
=> docs: Fix minor typos in headings

lib/resource/resource.ex
Change T to lowercase to match type
=> fix: Typo in name causing Error

documentation/topics/graphql-generation.md
=> Document how to query for errors in a mutation

test/read_test.exs
The same error I had last time #80 also happens now when I do the same thing but inside a union.
=> add test for loading stuff through unions with fragments

lib/ash_graphql.ex
=> fix: {:array, UnionType} issues resolving embedded types

test/read_test.exs, test/support/resources/user.ex
I updated the test to match my expectations. The assertion didn't do anything before. I changed the attribute on the resource to be non-nullable to show the problem with masking in the case of GraphQL.
=> update field policy test

lib/resource/resource.ex
without it they return empty values
=> fix(array unions): for arrays of embedded types unions when graphql_unnested_unions is used

lib/resource/resource.ex
[discussion link](https://discord.com/channels/711271361523351632/712035333432147989/1158029464899440650)
=> Add a top-level NOT filter, along with AND and OR filters.

test/generic_actions_test.exs
=> chore: add better regression test

lib/api/api.ex, lib/resource/resource.ex, test/errors_test.exs
Last point left from the discussion on #105
=> improvement: make the items of fields and errors non-null

.formatter.exs, documentation/dsls/DSL:-AshGraphql.Resource.md, lib/resource/resource.ex
- Regenerate formatter and cheatsheets for paginate_with
- Fix credo errors
=> chore: fix CI failures

documentation/how_to/upgrade.md
=> docs: Add upgrade note about changing `api` -> `domain`

.formatter.exs, documentation/dsls/DSL:-AshGraphql.Resource.md, lib/resource/mutation.ex, lib/resource/query.ex, lib/resource/resource.ex, test/resource_test.exs, test/support/resources/post.ex
=> feat: allow passing custom descriptions to queries and mutations

test/alias_test.exs, test/support/resources/post.ex
I found another problem while upgrading to 3.0
=> add test that shows problem with new auth field clean up

lib/error.ex
=> Implement AshGraphql.Error for Ash.Error.Query.ReadActionRequiresActor

documentation/tutorials/getting-started-with-graphql.md
Add ... to indicate previous code should remain in file.
=> Added clarification to Queries & Mutations on the Domain

lib/resource/resource.ex
=> add resource query to action struct

test/read_test.exs
Updates the forbidden field test to include public attributes (currently failing)
=> Add (failing) test for partial results of forbidden field query

lib/mix/tasks/ash_graphql.install.ex
Some minor tweaks around generated content, including a nicer sample query to be generated in the Schema module.
I think longer-term there are some discussions to be had around setting up the schema in the `app_web` folder and `AppWeb` namespace for Phoenix apps, but this is great for now to automate all the copy-paste setup!
=> chore: Wording tweaks to installer content

documentation/topics/handle-errors.md
=> Mention AshGraphl.Error Protocol in docs

config/config.exs, documentation/topics/use-subscriptions-with-graphql.md, lib/graphql/resolver.ex, lib/subscription/batcher.ex, lib/subscription/runner.ex, test/subscription_test.exs
=> Subscription batcher finish

lib/resource/mutation.ex
- https://github.com/ash-project/ash_graphql/issues/249
=> Allow Adding :description to :update and :destroy Mutation in AshGraphQL

documentation/topics/use-subscriptions-with-graphql.md
=> fix config reference in subscription docs

lib/resource/resource.ex, lib/subscriptions.ex
* pass nested correctly to get the right loads
* calculate the action types correctly for type gen
=> fix: subscription bugs

test/resource_test.exs, test/support/resources/comment.ex, test/support/types/map_with_embedded_resource.ex
Tests that map types can be made with resources inside
=> Test making a newtype with a resource as a struct inside

lib/graphql/resolver.ex
=> fix: Read graphql domain as provided by  AshGraphql.Graphql.DomainMiddleware 

lib/resource/resource.ex
It is a refactor but, again, there is a fix included.
- The fix (a little bit breakish): when getting an override type for an argument - [the override name](https://github.com/ash-project/ash_graphql/blob/e7c267a7b07d9bf4e89fb905ab99b002fe07b2f9/lib/resource/resource.ex#L1488) (if present) was used instead of original. I think original should be used, as, for example, it [gets used](https://github.com/ash-project/ash_graphql/blob/e7c267a7b07d9bf4e89fb905ab99b002fe07b2f9/lib/resource/resource.ex#L4720-L4724) for attribute type overrides.
- There was inconsistency in what is used for argument field identifier - original name or override - looking at codebase it seems that it should be the original.
- There was an [unreachable code path](https://github.com/ash-project/ash_graphql/blob/e7c267a …
=> fix: refactor internal `AshGraphql.Resource.mutation_fields/5`

lib/resource/resource.ex
Just refactor, no fixes here. Mutation definitions were mostly the same and the same code was repeated multiple times. Difference between create/update/destroy was only absence of identity/read arguments for create.
But note for future - I noticed that `argument_input_types` does not apply to read action arguments right now.
=> fix: refactor internal `AshGraphql.Resource.mutation/6`

.formatter.exs, lib/resource/info.ex, lib/resource/resource.ex, test/create_test.exs, test/filter_sort_test.exs, test/support/resources/tag.ex
PR for https://github.com/ash-project/ash_graphql/issues/330
=> Add sortable_fields option

lib/resource/resource.ex
=> Add sorting of managed inputs to output stable graphql schema

lib/graphql/resolver.ex, test/destroy_test.exs
=> Fixes bug 345

lib/domain/domain.ex
Credit goes to @dylantf for finding this bug.
- [ x] I accept the [AI Policy](https://github.com/ash-project/.github/blob/main/AI_POLICY.md), or AI was not used in the creation of this PR.
=> Fix typo in sort blueprint declaration

test/support/domain.ex, test/support/resources/resource_with_union.ex, test/union_test.exs
=> add test for union with typedstruct union-member that fails to compile

documentation/topics/use-struct-types-with-graphql.md
=> added documentation for how to add and use structured GraphQL types for standalone struct arguments
